name: build

on:

  schedule:
    - cron:  '0 0/12 * * *'

  push:
    branches: [ master ]

jobs:

  spark-images:

      name: Spark Images
      runs-on: ubuntu-latest
      env:
        HADOOP_VERSION: "2.7"
        SCALA_VERSION: "2.12.11"
        DOCKERHUB_USR: ${{ secrets.DOCKERHUB_USR }}
        DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}

      steps:

        - name: Checkout Code
          uses: actions/checkout@master

        - name: Build Base Image
          run: |
            cd ${GITHUB_WORKSPACE}/build
            docker build \
              --build-arg build_date="$(date -u +'%Y-%m-%d')" \
              --build-arg scala_version="${SCALA_VERSION}" \
              -f docker/base/Dockerfile \
              -t base:latest .

        - name: Build Spark Base Image - Spark v3.0.0 (latest)
          env:
            SPARK_VERSION: "3.0.0"
          run: |
            cd ${GITHUB_WORKSPACE}/build
            docker build \
              --build-arg build_date="$(date -u +'%Y-%m-%d')" \
              --build-arg spark_version="${SPARK_VERSION}" \
              --build-arg hadoop_version="${HADOOP_VERSION}" \
              -f docker/spark-base/Dockerfile \
              -t spark-base:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} .

        - name: Build & Push Spark Master Image - Spark v3.0.0 (latest)
          env:
            SPARK_VERSION: "3.0.0"
          run: |
            cd ${GITHUB_WORKSPACE}/build
            docker build \
              --build-arg build_date="$(date -u +'%Y-%m-%d')" \
              --build-arg spark_version="${SPARK_VERSION}" \
              --build-arg hadoop_version="${HADOOP_VERSION}" \
              -f docker/spark-master/Dockerfile \
              -t spark-master:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} .
            echo ${DOCKERHUB_PWD} | docker login -u ${DOCKERHUB_USR} --password-stdin
            docker tag spark-master:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} ${DOCKERHUB_USR}/spark-master:${SPARK_VERSION}-hadoop-${HADOOP_VERSION}
            docker push ${DOCKERHUB_USR}/spark-master:${SPARK_VERSION}-hadoop-${HADOOP_VERSION}
            docker tag spark-master:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} ${DOCKERHUB_USR}/spark-master:latest
            docker push ${DOCKERHUB_USR}/spark-master:latest

        - name: Build & Push Spark Worker Image - Spark v3.0.0 (latest)
          env:
            SPARK_VERSION: "3.0.0"
          run: |
            cd ${GITHUB_WORKSPACE}/build
            docker build \
              --build-arg build_date="$(date -u +'%Y-%m-%d')" \
              --build-arg spark_version="${SPARK_VERSION}" \
              --build-arg hadoop_version="${HADOOP_VERSION}" \
              -f docker/spark-worker/Dockerfile \
              -t spark-worker:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} .
            echo ${DOCKERHUB_PWD} | docker login -u ${DOCKERHUB_USR} --password-stdin
            docker tag spark-worker:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} ${DOCKERHUB_USR}/spark-worker:${SPARK_VERSION}-hadoop-${HADOOP_VERSION}
            docker push ${DOCKERHUB_USR}/spark-worker:${SPARK_VERSION}-hadoop-${HADOOP_VERSION}
            docker tag spark-worker:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} ${DOCKERHUB_USR}/spark-worker:latest
            docker push ${DOCKERHUB_USR}/spark-worker:latest

        - name: Build Spark Base Image - Spark v2.4.4
          env:
            SPARK_VERSION: "2.4.4"
          run: |
            cd ${GITHUB_WORKSPACE}/build
            docker build \
              --build-arg build_date="$(date -u +'%Y-%m-%d')" \
              --build-arg spark_version="${SPARK_VERSION}" \
              --build-arg hadoop_version="${HADOOP_VERSION}" \
              -f docker/spark-base/Dockerfile \
              -t spark-base:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} .

        - name: Build & Push Spark Master Image - Spark v2.4.4
          env:
            SPARK_VERSION: "2.4.4"
          run: |
            cd ${GITHUB_WORKSPACE}/build
            docker build \
              --build-arg build_date="$(date -u +'%Y-%m-%d')" \
              --build-arg spark_version="${SPARK_VERSION}" \
              --build-arg hadoop_version="${HADOOP_VERSION}" \
              -f docker/spark-master/Dockerfile \
              -t spark-master:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} .
            echo ${DOCKERHUB_PWD} | docker login -u ${DOCKERHUB_USR} --password-stdin
            docker tag spark-master:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} ${DOCKERHUB_USR}/spark-master:${SPARK_VERSION}-hadoop-${HADOOP_VERSION}
            docker push ${DOCKERHUB_USR}/spark-master:${SPARK_VERSION}-hadoop-${HADOOP_VERSION}

        - name: Build & Push Spark Worker Image - Spark v2.4.4
          env:
            SPARK_VERSION: "2.4.4"
          run: |
            cd ${GITHUB_WORKSPACE}/build
            docker build \
              --build-arg build_date="$(date -u +'%Y-%m-%d')" \
              --build-arg spark_version="${SPARK_VERSION}" \
              --build-arg hadoop_version="${HADOOP_VERSION}" \
              -f docker/spark-worker/Dockerfile \
              -t spark-worker:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} .
            echo ${DOCKERHUB_PWD} | docker login -u ${DOCKERHUB_USR} --password-stdin
            docker tag spark-worker:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} ${DOCKERHUB_USR}/spark-worker:${SPARK_VERSION}-hadoop-${HADOOP_VERSION}
            docker push ${DOCKERHUB_USR}/spark-worker:${SPARK_VERSION}-hadoop-${HADOOP_VERSION}

        - name: Build Spark Base Image - Spark v2.4.0
          env:
            SPARK_VERSION: "2.4.0"
          run: |
            cd ${GITHUB_WORKSPACE}/build
            docker build \
              --build-arg build_date="$(date -u +'%Y-%m-%d')" \
              --build-arg spark_version="${SPARK_VERSION}" \
              --build-arg hadoop_version="${HADOOP_VERSION}" \
              -f docker/spark-base/Dockerfile \
              -t spark-base:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} .

        - name: Build & Push Spark Master Image - Spark v2.4.0
          env:
            SPARK_VERSION: "2.4.0"
          run: |
            cd ${GITHUB_WORKSPACE}/build
            docker build \
              --build-arg build_date="$(date -u +'%Y-%m-%d')" \
              --build-arg spark_version="${SPARK_VERSION}" \
              --build-arg hadoop_version="${HADOOP_VERSION}" \
              -f docker/spark-master/Dockerfile \
              -t spark-master:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} .
            echo ${DOCKERHUB_PWD} | docker login -u ${DOCKERHUB_USR} --password-stdin
            docker tag spark-master:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} ${DOCKERHUB_USR}/spark-master:${SPARK_VERSION}-hadoop-${HADOOP_VERSION}
            docker push ${DOCKERHUB_USR}/spark-master:${SPARK_VERSION}-hadoop-${HADOOP_VERSION}

        - name: Build & Push Spark Worker Image - Spark v2.4.0
          env:
            SPARK_VERSION: "2.4.0"
          run: |
            cd ${GITHUB_WORKSPACE}/build
            docker build \
              --build-arg build_date="$(date -u +'%Y-%m-%d')" \
              --build-arg spark_version="${SPARK_VERSION}" \
              --build-arg hadoop_version="${HADOOP_VERSION}" \
              -f docker/spark-worker/Dockerfile \
              -t spark-worker:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} .
            echo ${DOCKERHUB_PWD} | docker login -u ${DOCKERHUB_USR} --password-stdin
            docker tag spark-worker:${SPARK_VERSION}-hadoop-${HADOOP_VERSION} ${DOCKERHUB_USR}/spark-worker:${SPARK_VERSION}-hadoop-${HADOOP_VERSION}
            docker push ${DOCKERHUB_USR}/spark-worker:${SPARK_VERSION}-hadoop-${HADOOP_VERSION}

  jupyterlab-images:

    name: JupyterLab Images
    runs-on: ubuntu-latest
    env:
      SCALA_VERSION: "2.12.11"
      JUPYTERLAB_VERSION: "2.1.4"
      DOCKERHUB_USR: ${{ secrets.DOCKERHUB_USR }}
      DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@master

      - name: Build Base Image
        run: |
          cd ${GITHUB_WORKSPACE}/build
          docker build \
            --build-arg build_date="$(date -u +'%Y-%m-%d')" \
            --build-arg scala_version="${SCALA_VERSION}" \
            -f docker/base/Dockerfile \
            -t base:latest .

      - name: Build & Push JupyterLab Image - Spark v3.0.0 (latest)
        env:
          SPARK_VERSION: "3.0.0"
        run: |
          cd ${GITHUB_WORKSPACE}/build
          docker build \
            --build-arg build_date="$(date -u +'%Y-%m-%d')" \
            --build-arg scala_version="${SCALA_VERSION}" \
            --build-arg spark_version="${SPARK_VERSION}" \
            --build-arg jupyterlab_version="${JUPYTERLAB_VERSION}" \
            -f docker/jupyterlab/Dockerfile \
            -t jupyterlab:${JUPYTERLAB_VERSION}-spark-${SPARK_VERSION} .
          echo ${DOCKERHUB_PWD} | docker login -u ${DOCKERHUB_USR} --password-stdin
          docker tag jupyterlab:${JUPYTERLAB_VERSION}-spark-${SPARK_VERSION} ${DOCKERHUB_USR}/jupyterlab:${JUPYTERLAB_VERSION}-spark-${SPARK_VERSION}
          docker push ${DOCKERHUB_USR}/jupyterlab:${JUPYTERLAB_VERSION}-spark-${SPARK_VERSION}
          docker tag jupyterlab:${JUPYTERLAB_VERSION}-spark-${SPARK_VERSION} ${DOCKERHUB_USR}/jupyterlab:latest
          docker push ${DOCKERHUB_USR}/jupyterlab:latest

      - name: Build & Push JupyterLab Image - Spark v2.4.4
        env:
          SPARK_VERSION: "2.4.4"
        run: |
          cd ${GITHUB_WORKSPACE}/build
          docker build \
            --build-arg build_date="$(date -u +'%Y-%m-%d')" \
            --build-arg scala_version="${SCALA_VERSION}" \
            --build-arg spark_version="${SPARK_VERSION}" \
            --build-arg jupyterlab_version="${JUPYTERLAB_VERSION}" \
            -f docker/jupyterlab/Dockerfile \
            -t jupyterlab:${JUPYTERLAB_VERSION}-spark-${SPARK_VERSION} .
          echo ${DOCKERHUB_PWD} | docker login -u ${DOCKERHUB_USR} --password-stdin
          docker tag jupyterlab:${JUPYTERLAB_VERSION}-spark-${SPARK_VERSION} ${DOCKERHUB_USR}/jupyterlab:${JUPYTERLAB_VERSION}-spark-${SPARK_VERSION}
          docker push ${DOCKERHUB_USR}/jupyterlab:${JUPYTERLAB_VERSION}-spark-${SPARK_VERSION}

      - name: Build & Push JupyterLab Image - Spark v2.4.0
        env:
          SPARK_VERSION: "2.4.0"
        run: |
          cd ${GITHUB_WORKSPACE}/build
          docker build \
            --build-arg build_date="$(date -u +'%Y-%m-%d')" \
            --build-arg scala_version="${SCALA_VERSION}" \
            --build-arg spark_version="${SPARK_VERSION}" \
            --build-arg jupyterlab_version="${JUPYTERLAB_VERSION}" \
            -f docker/jupyterlab/Dockerfile \
            -t jupyterlab:${JUPYTERLAB_VERSION}-spark-${SPARK_VERSION} .
          echo ${DOCKERHUB_PWD} | docker login -u ${DOCKERHUB_USR} --password-stdin
          docker tag jupyterlab:${JUPYTERLAB_VERSION}-spark-${SPARK_VERSION} ${DOCKERHUB_USR}/jupyterlab:${JUPYTERLAB_VERSION}-spark-${SPARK_VERSION}
          docker push ${DOCKERHUB_USR}/jupyterlab:${JUPYTERLAB_VERSION}-spark-${SPARK_VERSION}